add params grouping functions in model.utils.
PaddlePaddle/PASSL pull request #155
Opened 2023-04-24 02:44 UTC by qizhaoaoe

1. add group_with_matcher;
2. add group_param_layer_decay and param_group_weight_decay.

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/engine/engine.py
> +        self.lr_decay_unit = self.config["Optimizer"].get("decay_unit", 'step')
这里为什么是 Optimizer 的 decay_unit ? Optimizer decay 什么？

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/optimizer/__init__.py
> +                    group_matcher = re.compile(g_name)
这里拿 group name 当正则表达式了？

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/optimizer/__init__.py
> +                if 'others' not in params_dict:
起个 default 关键字吧，others 不合适。

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/optimizer/__init__.py
> +    return {'grad': {"params": param_groups}}
这个 grad 我是没看懂什么意思

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/optimizer/__init__.py
> +        new_cfg.update({
这里的 update 没看懂是为什么

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/optimizer/__init__.py
> +        param_group_map = model.param_groups(no_weight_decay_name, **new_cfg)
你这里 **new_cfg 会发生什么？里面有哪些参数谁知道？

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/optimizer/optimizer.py
> +    def __init__(self, params, defaults, learning_rate=0.1):
这里为什么要增加 learning_rate=0.1？

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/optimizer/optimizer.py
> +                    if default is not None:
default is not None 什么时候会变成 None？会发生吗？

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/optimizer/utils/group_params.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
怎么这里还有个一模一样的 代码？

2023-04-26 02:41 UTC, GuoxiaWang commented on tasks/ssl/cae/util/lr_sched.py
> +        param_group["lr"] = lr
为什么会影响到这里？

2023-04-26 02:41 UTC, GuoxiaWang commented on tasks/ssl/simsiam/configs/simsiam_resnet50_pt_in1k_1n8c_dp_fp32.yaml
> +  decay_unit: epoch
同上，为什么 Optimizer 有 decay_unit 属性，这个属性难道不是 lr scheduler的 吗？

2023-04-26 02:41 UTC, GuoxiaWang commented on tasks/ssl/simsiam/configs/simsiam_resnet50_pt_in1k_1n8c_dp_fp32.yaml
> +    - name: backbone
如果是没有看过源码和参与讨论的同学，是看不懂这里的。 backbone 的分组用的是regular_exp， 下面predictor 却不用 regular_exp 而是用 name 当成 regular_exp 来使用了。

2023-04-26 02:41 UTC, GuoxiaWang commented on passl/optimizer/__init__.py
> +            if param.stop_gradient:
这有个问题，好像所有的分组，都通过 param.stop_gradient 把这些参数过滤掉了。后面要用怎么办？

2023-04-26 02:46 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +                    group_matcher = re.compile(g_name)
是的，如果没有指定的regular_exp的话，这样为了统一下面的过滤逻辑。

2023-04-26 02:47 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +    return {'grad': {"params": param_groups}}
这个是默认的分组，仅仅保留有梯度的参数。

2023-04-26 02:48 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +        new_cfg.update({
把config和其他可能用到的参数传给模型，自定义分组策略。

2023-04-26 02:49 UTC, shiyutang commented on passl/engine/engine.py
> +        self.lr_decay_unit = self.config["Optimizer"].get("decay_unit", 'step')
这个是因为不同的lr scheduler需要统一step的方式，或者这里可以理解为optimizer更新学习率的频率么

2023-04-26 02:50 UTC, qizhaoaoe commented on tasks/ssl/cae/util/lr_sched.py
> +        param_group["lr"] = lr
optimizer加了默认的_get_lr()方法，添加了这个判断逻辑。

2023-04-26 02:52 UTC, qizhaoaoe commented on passl/engine/engine.py
> +        self.lr_decay_unit = self.config["Optimizer"].get("decay_unit", 'step')
这个是lr_decay_unit，因为lr已经变成了optimizer的属性，可以只是一个float，所以就添加到optimizer中了，可以改成“lr_decay_unit”

2023-04-26 02:52 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +                if 'others' not in params_dict:
好的。

2023-04-26 02:53 UTC, qizhaoaoe commented on passl/optimizer/utils/group_params.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
models.utils.group_params需要删除。

2023-04-26 02:58 UTC, qizhaoaoe commented on tasks/ssl/simsiam/configs/simsiam_resnet50_pt_in1k_1n8c_dp_fp32.yaml
> +    - name: backbone
好的，这个确实没有必要用regular_exp, 后期可以在config的文档中体现出来。

2023-04-26 03:03 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +            if param.stop_gradient:
考虑到optimizer只是针对于有梯度的参数，如果后期有需求可以再改逻辑吧。

2023-04-26 03:13 UTC, qizhaoaoe commented on passl/engine/engine.py
> +        self.lr_decay_unit = self.config["Optimizer"].get("decay_unit", 'step')
这个decay_unit是一个engine获取的全局变量，分组中的lr应该是共用这个变量的，每个分组中的lr都有一个decay_unit，这个场景应该比较少见的，所以放到optimizer中来也是合理的。

2023-04-26 03:19 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +    return {'grad': {"params": param_groups}}
已经修改为default

2023-04-26 03:23 UTC, qizhaoaoe commented on passl/optimizer/optimizer.py
> +                    if default is not None:
实验了，只要没有lrscheduler的section（没有强制要求有），就会传给optimizer一个None，会出错。

2023-04-26 03:26 UTC, qizhaoaoe commented on passl/optimizer/optimizer.py
> +    def __init__(self, params, defaults, learning_rate=0.1):
如果没有lrscheduler的section（没有强制要求有），就会传给optimizer一个None的lr，会出错，所以加了一个默认值。

2023-04-26 04:13 UTC, shiyutang requested changes
初步在代码提出几点修改建议。

2023-04-26 04:13 UTC, shiyutang commented on passl/optimizer/__init__.py
> +
这段代码和engine中build_lr_scheduler重复了～

2023-04-26 04:13 UTC, shiyutang commented on passl/optimizer/__init__.py
>          lr_func = lr_scheduler
这里lr_func更新成了lr_scheduler，但是optimizer里面不会使用lr_func.step而是直接使用call方式，不确定paddle.optimizer.lr.lr_scheduler能不能这样调用。
<img width="567" alt="image" src="https://user-images.githubusercontent.com/34859558/234467541-9f07aada-7872-42d8-894d-290c8007e80e.png">

2023-04-26 04:13 UTC, shiyutang commented on passl/optimizer/optimizer.py
> +    def __init__(self, params, defaults, learning_rate=0.1):
按理应该不会，build lr scheduler的时候会默认传回lr，这个回传的参数是不是直接传入optimizer就可以了，optimizer的lr是数值/lr-scheduler，就不用这样写了，后面也有一个类似的兼容问题可以同时解决。
<img width="602" alt="image" src="https://user-images.githubusercontent.com/34859558/234467974-da798224-3392-411c-b542-4bea2034542d.png">

2023-04-26 05:16 UTC, qizhaoaoe commented on passl/engine/engine.py
> +        self.lr_decay_unit = self.config["Optimizer"].get("decay_unit", 'step')
好的。

2023-04-26 05:17 UTC, qizhaoaoe commented on passl/engine/engine.py
>                      len(self.train_dataloader))
这里目前并没有删除外层的lr_scheduler，因为要修改其他的模型，下个pr可以删掉这个。

2023-04-26 05:17 UTC, qizhaoaoe commented on passl/models/utils/group_params.py
> +        assert re_exps is not None
好的。

2023-04-26 05:17 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +            'layer_decay': layer_decay,
好的。

2023-04-26 05:19 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +        param_group_map = model.param_groups(no_weight_decay_name, **new_cfg)
tensor fusion不放到model里去做了，在自定义分组之后加上针对于tensor_fusion的再次划分，放到build_optimizer里实现了。

2023-04-26 05:19 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +
这段代码也是兼容了之前lr_scheduler section的考虑，下个pr可以删掉engine中的。

2023-04-26 06:06 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
>          lr_func = lr_scheduler
在build_optimizer中做了check。
![image](https://user-images.githubusercontent.com/10208099/234484118-36942fd7-0505-48c0-b224-1a64bc262b11.png)

2023-04-26 06:25 UTC, qizhaoaoe commented on passl/engine/engine.py
> +        self.lr_decay_unit = self.config["Optimizer"].get("decay_unit", 'step')
已修改

2023-04-26 06:45 UTC, qizhaoaoe commented on passl/engine/engine.py
> +        self.lr_decay_unit = self.config["Optimizer"].get("decay_unit", 'step')
@shiyutang 是的，这个lr_decay_unit并没有在build_lr_sheduler中使用，只是在loop中使用，选择更新lr的频率。

2023-04-26 07:19 UTC, shiyutang commented on passl/optimizer/__init__.py
> +        param_group_map = model.param_groups(no_weight_decay_name, **new_cfg)
但是没在build_optimizer看到呢？

2023-04-27 02:47 UTC, GuoxiaWang requested changes

2023-04-27 02:47 UTC, GuoxiaWang commented on passl/optimizer/__init__.py
> +        model_group_cfg = config.pop('model_param_groups', {})
`model_param_groups` 改个名，改成 `model_group_cfg = config.pop('param_group_fn', {})`

2023-04-27 02:47 UTC, GuoxiaWang commented on passl/optimizer/__init__.py
> +        param_group_map = model.param_group_fn(no_weight_decay_name, weight_decay, layer_decay, model_group_cfg)
` param_group_map = model.param_group_fn(no_weight_decay_name=no_weight_decay_name, weight_decay=weight_decay, layer_decay=layer_decay, **model_group_cfg)`

2023-04-27 02:47 UTC, GuoxiaWang commented on passl/optimizer/__init__.py
> +        param_group_map = group_param_by_config(model, config, epochs, step_each_epoch)
这里其实是可以提前把 lr 相关的 build 好。就不用传 epochs, step_each_epoch 进去了。

2023-04-27 06:23 UTC, GuoxiaWang approved these changes
LGTM

2023-04-27 06:51 UTC, shiyutang commented on passl/optimizer/__init__.py
> +            lr_scheduler = build_lr_scheduler(lr_cfg, epochs, step_each_epoch)
这里不需要传decay-unit么

2023-04-27 07:24 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +            lr_scheduler = build_lr_scheduler(lr_cfg, epochs, step_each_epoch)
在lr_cfg中添加。

2023-04-27 07:38 UTC, GuoxiaWang requested changes

2023-04-27 08:18 UTC, qizhaoaoe commented on passl/optimizer/__init__.py
> +            lr_scheduler = build_lr_scheduler(lr_cfg, epochs, step_each_epoch)
如果没设置，就用lr_decay_unit赋值了。

2023-04-27 08:24 UTC, GuoxiaWang submitted a review, later dismissed
LGTM

2023-04-27 08:55 UTC, shiyutang commented on passl/optimizer/__init__.py
>                      f'decay_unit has to be equal to "{lr_decay_unit}" that set in lr_decay_unit.'
如果需要assert 每一组都一样，那么decay_unit只需要存在optimizer里就可以了，也就是不建议也不访问在param_group中的decay_unit属性。

下面这行确保了optimizer中的decay_unit存在，因此可以直接使用optimizer中的。https://github.com/PaddlePaddle/PASSL/blob/368410069fad9ce9db9657db95b017eea748e715/passl/engine/engine.py#L217

因此可以将L55-L59替换成
```
lr_cfg['decay_unit'] = lr_decay_unit
```

2023-04-27 08:55 UTC, shiyutang commented on passl/optimizer/__init__.py
>                  f'decay_unit has to be equal to "{lr_decay_unit}" that set in lr_decay_unit.'
两个一样的assetation，其实重复了。

2023-04-28 01:57 UTC, shiyutang approved these changes
LGTM

2023-04-28 03:21 UTC, merged