[Feature] Add SwAV
PaddlePaddle/PASSL pull request #156
Opened 2023-04-24 07:42 UTC by shiyutang

2023-04-24 07:46 UTC, GuoxiaWang requested changes

2023-04-24 07:46 UTC, GuoxiaWang commented on passl/data/preprocess/basic_transforms.py
> +class GaussianBlur(object):
`SimCLRGaussianBlur` 已经实现了

2023-04-24 07:46 UTC, GuoxiaWang commented on passl/engine/loops/classification_loop.py
> +class LogFormatter:
Logger 是临时调试还是？logger 是已经有的

2023-04-24 08:06 UTC, shiyutang commented on passl/engine/loops/classification_loop.py
> +class LogFormatter:
临时调试的

2023-05-06 02:04 UTC, shiyutang commented on passl/data/preprocess/basic_transforms.py
> +class GaussianBlur(object):
don e

2023-05-06 02:04 UTC, shiyutang commented on passl/engine/loops/classification_loop.py
> +class LogFormatter:
removed

2023-05-11 02:39 UTC, GuoxiaWang requested changes

2023-05-11 02:39 UTC, GuoxiaWang commented on passl/models/swav_resnet.py
> +class SwAVResNet(paddle.nn.Layer):
把这个文件的代码挪到 swav.py  中，删除 swav_resnet.py

2023-05-11 02:39 UTC, GuoxiaWang commented on passl/engine/loops/contrastive_learning_loop.py
> +            try:
这个地方可以去掉，不用传入 total_iterations。 相关的变量从 `runtime_info_hub` 中获取，如果没有新增一下。

2023-05-11 02:39 UTC, GuoxiaWang commented on passl/engine/engine.py
> +            if  self.config["Global"]["pretrained_model"] is not None:
这里是什么原因导致有缩进

2023-05-11 02:39 UTC, GuoxiaWang commented on passl/data/dataset/imagefolder_dataset.py
> +        if samples_tag is None:
这一些代码，是否可以在子类中重写？而不修改基类 `ImageFolder`

2023-05-11 02:39 UTC, GuoxiaWang commented on passl/engine/loops/loop.py
> +            self.train_one_epoch(epoch_id)
epoch_id 其实可以从 trainer 中获取，没必要传参数

2023-05-11 02:39 UTC, GuoxiaWang commented on passl/scheduler/__init__.py
> +        if "MultiStepDecay" in lr_name:
其实这里没必要加这个 if，只要在 MultiStepDecay 中加 **kwargs 即可，不会有影响的。

2023-05-15 06:13 UTC, shiyutang commented on passl/engine/loops/contrastive_learning_loop.py
> +                self.trainer.model.after_loss_backward(self.total_iterations)
在model的forward里面进行尝试

2023-05-16 07:35 UTC, GuoxiaWang commented on passl/engine/loops/loop.py
> +            runtime_info_hub.total_iterations = (self.trainer.cur_epoch_id-1)*self.total_batch_idx + batch_idx
这个地方是不是等同于 global_steps?

2023-05-16 07:38 UTC, GuoxiaWang commented on passl/data/dataset/multicrop_dataset.py
> +        color_transform = [get_color_distortion(), get_pil_gaussian_blur()]
为什么这个地方还有写死的操作？

2023-05-16 08:44 UTC, GuoxiaWang commented on passl/engine/loops/loop.py
> +            runtime_info_hub.total_iterations = (self.trainer.cur_epoch_id-1)*self.total_batch_idx + batch_idx
在 engine.py 里面

2023-05-18 02:01 UTC, GuoxiaWang commented on passl/data/dataset/fewshot_dataset.py
> +        print('Previous information is not correct.')
print  改成 logger.info 吧

2023-05-18 02:05 UTC, GuoxiaWang commented on passl/models/swav.py
> +        self.res_model.eval()
这几个 res_model 起名是否可以换一个更通用的？比如 backbone 或者 encoder 也行，虽然SwAV 中就是resnet

2023-05-18 02:06 UTC, GuoxiaWang commented on passl/models/swav.py
> +            # with apex syncbn speeds up computation than global syncbn
这个 apex 是否有必要？

2023-05-18 02:08 UTC, GuoxiaWang commented on passl/models/swav.py
> +class RegLog(paddle.nn.Layer):
这个 RegLog 改成 RegLogit 是不是会更清晰，我第一次读的时候以为是一个 log 相关的。

2023-05-18 02:11 UTC, GuoxiaWang commented on tasks/ssl/swav/README.md
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
README 中为什么会有这些代码？

2023-05-18 02:12 UTC, GuoxiaWang commented on tests/CI/case.sh
> +    if [ $1 == swav_resnet50_224_pt_in1k_1n8c_dp_fp16o1 ];then
这里专门为 swav_resnet50_224_pt_in1k_1n8c_dp_fp16o1 写了个分支，目的是什么？

2023-05-18 02:15 UTC, shiyutang commented on tasks/ssl/swav/README.md
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
removed～

2023-05-18 02:15 UTC, shiyutang commented on passl/models/swav.py
> +class RegLog(paddle.nn.Layer):
好的～

2023-05-18 02:16 UTC, shiyutang commented on passl/models/swav.py
> +            # with apex syncbn speeds up computation than global syncbn
有可能会加速，但是还没有实验，可以保留用于后续实验。

2023-05-18 02:17 UTC, shiyutang commented on passl/models/swav.py
> +        self.res_model.eval()
可以改，但是训练的参数可能加载不上了

2023-05-18 02:19 UTC, GuoxiaWang commented on passl/models/swav.py
> +        self.res_model.eval()
那先不改了把。有空可以改，不用再重新训练，只需要把 checkpoint 加载起来，换个key就行。

2023-05-18 02:19 UTC, shiyutang commented on passl/data/dataset/fewshot_dataset.py
> +        print('Previous information is not correct.')
done

2023-05-18 02:19 UTC, shiyutang commented on tests/CI/case.sh
> +    if [ $1 == swav_resnet50_224_pt_in1k_1n8c_dp_fp16o1 ];then
因为单机八卡总是会差一点，没有办法固定所有权重。

2023-05-18 02:23 UTC, shiyutang commented on passl/data/dataset/multicrop_dataset.py
> +        color_transform = [get_color_distortion(), get_pil_gaussian_blur()]
这个数据集的功能就是实现SwAV提出的数据增强，感觉不是很需要配置的方式。

2023-05-18 02:25 UTC, GuoxiaWang commented on passl/data/dataset/multicrop_dataset.py
> +        color_transform = [get_color_distortion(), get_pil_gaussian_blur()]
那在类名上加个前缀吧。这样就是特定的数据集。

2023-05-18 02:28 UTC, GuoxiaWang commented on passl/engine/loops/loop.py
> +            runtime_info_hub.total_iterations = (self.trainer.cur_epoch_id-1)*self.total_batch_idx + batch_idx
在 engine 中
```
    @property
    def global_step(self):
        return self.train_loop.global_step
```

2023-05-18 02:48 UTC, shiyutang commented on passl/data/dataset/multicrop_dataset.py
> +        color_transform = [get_color_distortion(), get_pil_gaussian_blur()]
好的～

2023-05-19 07:48 UTC, GuoxiaWang approved these changes
LGTM

2023-05-19 07:48 UTC, merged